import { describe, expect, it } from "vitest";

import { neverAutoAllow } from "../src/never.js";

const check = (command: string) => neverAutoAllow({ command });

describe("neverAutoAllow", () => {
  it.each([
    ["crontab -e", "changes scheduled jobs"],
    ["echo 'make build' | at now", "changes scheduled jobs"],
    ["systemctl --user enable dev.service", "adds a background service"],
    ["launchctl load ~/Library/LaunchAgents/dev.plist", "adds a background service"],
    ["security add-trusted-cert -d root.pem", "weakens platform security"],
    ["curl -sk https://localhost/health", "turns off certificate checks"],
    ["NODE_TLS_REJECT_UNAUTHORIZED=0 pnpm test", "turns off certificate checks"],
    [
      "aws s3 ls --no-verify-ssl --endpoint-url https://minio.local",
      "turns off certificate checks",
    ],
    ["podman push --tls-verify=false localhost:5000/img", "turns off certificate checks"],
    ["pip install --trusted-host files.example.com pkg", "turns off certificate checks"],
    ["PYTHONHTTPSVERIFY=0 python fetch.py", "turns off certificate checks"],
    ["ssh -o StrictHostKeyChecking=no deploy@host uptime", "turns off SSH host key checks"],
    ["ssh -o 'StrictHostKeyChecking no' deploy@host", "turns off SSH host key checks"],
    ["ssh -o StrictHostKeyChecking=false example.com true", "turns off SSH host key checks"],
    ["http --verify=no https://example.com", "turns off certificate checks"],
    ["brew services start postgresql@17", "adds a background service"],
    ["brew services restart redis", "adds a background service"],
    ["brew services --verbose start redis", "adds a background service"],
    ["brew services --file=dev.plist start redis", "adds a background service"],
    ["brew services --file dev.plist start redis", "adds a background service"],
    ["printf 'echo later\\n' | batch next minute", "changes scheduled jobs"],
    ["echo later | batch Dec 25", "changes scheduled jobs"],
    ["printf 'echo later\\n' | at Monday", "changes scheduled jobs"],
    ["printf 'echo later\\n' | batch mon", "changes scheduled jobs"],
    ['brew services --file "dev file.plist" start redis', "adds a background service"],
    ['brew services --file="./dev file name.plist" restart redis', "adds a background service"],
    ["printf 'echo later\\n' | at next minute", "changes scheduled jobs"],
    ["systemd-run --user --on-calendar=hourly ./backup.sh", "changes scheduled jobs"],
    [
      "GIT_SSH_COMMAND='ssh -o UserKnownHostsFile=/dev/null' git fetch",
      "turns off SSH host key checks",
    ],
  ])("gives %s its reason", (command, why) => {
    expect(check(command)).toBe(why);
  });

  // Shell syntax cannot hide a mention: wrappers, nested shells, heredocs, pipes into a
  // shell, redirections, and quote or line splits all still contain the words.
  it.each([
    "crontab -e",
    "launchctl load ~/Library/LaunchAgents/dev.plist",
    "systemctl --user enable dev.service",
    "NODE_TLS_REJECT_UNAUTHORIZED=0 pnpm test",
    "curl -sk https://api.example.com/health",
    "curl --insecure https://api.example.com/health",
    "npm config set strict-ssl false",
    "systemctl --now enable dev.service",
    'NODE_TLS_REJECT_UNAUTHORIZED="0" pnpm test',
    "curl https://localhost/health --insecure; echo done",
    "cd app && sudo crontab -e",
    "git config --global http.sslVerify false",
    "sudo -u root systemctl enable dev.service",
    "sudo --user root crontab -e",
    "env -u DEBUG NODE_TLS_REJECT_UNAUTHORIZED=0 pnpm test",
    "if true; then systemctl enable dev.service; fi",
    "for f in a b; do crontab -r; done",
    "timeout 5 curl -k https://localhost/health",
    "bash -lc 'systemctl enable dev.service'",
    'sh -c "eval \\"crontab -r\\""',
    "env -S 'systemctl enable' dev.service",
    "find . -name '*.plist' -exec launchctl load {} \\;",
    "echo $((1 << 2))\nsystemctl enable dev.service",
    "((a) && (crontab -r))",
    "cat <<EOF\nnow: $(crontab -r)\nEOF",
    "cat <<EOF\nno end\nsystemctl enable dev.service",
    "git -c http.sslVerify=false clone https://example.com/repo",
    'echo "now: $(crontab -r)"',
    "curl \\\n  --insecure https://localhost/health",
    "git config --global http.sslVerify \\\nfalse",
    "sudo \\\n  -u root systemctl enable dev.service",
    "NODE_TLS_REJECT_UNAUTHORIZED=\\\n0 pnpm test",
    'echo "a \\\n$(crontab -r)"',
    "su root -c 'systemctl enable dev.service'",
    "runuser -u root -- crontab -r",
    "tcsh -c 'systemctl enable dev.service'",
    "busybox sh -c 'crontab -r'",
    "echo 'make build' | at now",
    "watch -n 1 crontab -r",
    "watch 'crontab -r'",
    "setsid crontab -r",
    "cat <<EOF\n$(echo $(crontab -r))\nEOF",
    "runuser -u root -- git -c http.sslVerify=false push",
    "runuser -u root -- curl -c /tmp/jar --insecure https://x",
    "runuser -u root -- ssh -c aes128-ctr host; crontab -r",
    "bash -c'systemctl enable dev.service'",
    "bash -lc'crontab -r'",
    "su root -c'systemctl enable dev.service'",
    "su root --command='crontab -r'",
    "npm config set strict-ssl=false",
    "git config --global http.sslVerify 0",
    "git -c http.sslverify=off fetch",
    "GIT_SSL_NO_VERIFY=yes git pull",
    "atrm 3",
    "su root -- -c 'systemctl enable dev.service'",
    "su -- -c 'crontab -r'",
    "su -s /bin/bash root -- -c 'crontab -r'",
    "runuser deploy -- -c 'crontab -r'",
    "npm config set strict-ssl 0",
    "npm_config_strict_ssl=false npm install",
    "git -c alias.x='!crontab -r' x",
    "runuser --user=root -- crontab -r",
    "runuser --user=root -- systemctl enable dev.service",
    "su root -m -- -c 'crontab -r'",
    "su root -- crontab -r",
    "git config --global alias.ci '!crontab -r'",
    "git -c ALIAS.ci='!crontab -r' ci",
    "npm install --strict-ssl=false",
    "npm install --no-strict-ssl",
    "git config alias.ci ' !crontab -r'",
    "git -c 'alias.ci= !crontab -r' ci",
    "systemctl reenable dev.service",
    "GIT_SSL_NO_VERIFY=0 git fetch origin",
    "GIT_SSL_NO_VERIFY=false git fetch origin",
    "GIT_SSL_NO_VERIFY= git fetch origin",
    "export GIT_SSL_NO_VERIFY=",
    "bash <<'EOF'\ncrontab -r\nEOF",
    "cat <<'EOF' | bash\ncrontab -r\nEOF",
    "sudo sh <<EOF\nsystemctl enable dev.service\nEOF",
    "git -c http.sslVerify= fetch origin",
    "git config --global http.sslVerify ''",
    "git config set http.sslVerify false",
    "bash <<< 'crontab -r'",
    "sudo -u root bash <<< 'systemctl enable dev.service'",
    "git --git-dir .git -c http.sslVerify=false fetch origin",
    "git --work-tree . -c http.sslVerify= fetch origin",
    "git --git-dir .git config http.sslVerify false",
    "cat <<< 'crontab -r' | bash",
    "bash <<< ':' <<< 'crontab -r'",
    "bash -c '> /dev/null; crontab -r'",
    "bash -s <<< 'crontab -r'",
    "bash 0<<< 'crontab -r'",
    "bash 0<<'EOF'\ncrontab -r\nEOF",
    "curl -k>/dev/null https://example.com",
    "bash - <<< 'crontab -r'",
    "bash +e <<< 'crontab -r'",
    "bash --rcfile /dev/null <<< 'crontab -r'",
    "bash -o noexec +o noexec <<< 'crontab -r'",
    "bash <<EOF\necho '$(crontab -r)'\nEOF",
    "cat <<EOF\necho '$(crontab -r)'",
    "cat <<A <<B\nx\nA\necho '$(crontab -r)'",
    "su deploy -c 'sh' <<< 'crontab -r'",
    "su deploy -c 'sh' <<'EOF'\ncrontab -r\nEOF",
    "su deploy <<< 'crontab -r'",
    "echo 'crontab -r' | bash",
    "printf 'systemctl enable dev.service' | sudo sh",
    "sudo -s <<< 'crontab -r'",
    "sudo -i <<'EOF'\ncrontab -r\nEOF",
    "runuser -u deploy <<< 'crontab -r'",
    "runuser -s bash deploy <<< 'crontab -r'",
    "command echo 'crontab -r' | bash",
    "X=1 echo 'crontab -r' | sh",
    "eval \"$(echo 'crontab -r')\"",
    "git -c core.pager='crontab -r' log",
    "git config --global core.editor 'crontab -r'",
    "printf '%s\\n' 'crontab -r' | bash",
    "echo curl -k https://localhost | bash",
    "bash -e +u -c 'crontab -r'",
    "bash --rcfile /dev/null -c 'crontab -r'",
    "curl &>curl.log -k https://localhost",
    "curl -4k https://localhost",
    "curl -k4 https://localhost",
    "cat <<'EOF' |\ncrontab -r\nEOF\nbash",
    "git config set core.editor 'crontab -r'",
    "git config --type bool http.sslVerify false",
    "printf '%s\\n' 'echo \\\"' 'crontab -r' | bash",
    "printf 'git config http.sslVerify %d\\n' | bash",
    "printf 'git config http.sslVerify %d\\n' 0x0 | bash",
    "bash -c -O extglob 'crontab -r'",
    "printf 'crontab\\040-r\\n' | bash",
    "printf 'crontab\\x20-r\\n' | bash",
    "echo -e 'crontab\\x20-r' | bash",
    "printf '%b\\n' 'crontab\\040-r' | bash",
    "printf 'git config http.sslVerify %5s\\n' 0 | bash",
    "printf 'git config http.sslVerify %c\\n' 0 | bash",
    "printf 'git config http.sslVerify %x\\n' 0 | bash",
    "bash -c'batch'",
    "printf 'crontab% d\\n' 5 | bash",
    "printf 'atrm%#x\\n' 1 | bash",
    "printf 'crontab\\400 -r\\n' | bash",
    "printf 'crontab\\0401-r\\n' | bash",
    "echo -e 'crontab\\0400 -r' | bash",
    "printf 'git config http.sslVerify %d\\n' 18446744073709551616 | bash",
    "printf 'git config http.sslVerify %d\\n' -0x0 | bash",
    "printf 'crontab%cx\\n' | bash",
    "printf 'crontab%c\\n' '' | bash",
    "printf '%5%crontab\\n' | bash",
    "printf 'crontab%2s -r\\n' '😀' | bash",
    "crontab\u0000 -r",
    "bash -co posix 'crontab -r'",
    "bash -cl -- 'git config http.sslVerify false'",
    "git config set --comment --get http.sslVerify false",
    "cat <<'EOF' |# comment\ncrontab -r\nEOF\nbash",
    "git config --file .git/config http.sslVerify false",
    "git config set --value vim core.editor 'crontab -r'",
    "printf 'curl %s https://localhost\\n' '-k' | bash",
    "printf 'echo ready\\ncrontab -r\\n' | bash",
    "echo -e 'echo ready\\ncrontab -r' | bash",
    "cat <<'EOF' | # explanatory comment\ncrontab -r\nEOF\nbash",
    'echo "now: `systemctl enable dev.service`"',
    "crontab -r # -l",
    "cr$''ontab -r",
    "c$'ron'tab -r",
    "curl -H 'X-Debug: ;' -k https://localhost/health",
    "curl -H 'X-Debug: |' -k https://localhost/health",
    "systemctl --root='/tmp/a;b' enable dev.service",
    "TZ=UTC at -f job.sh now",
    "/usr/bin/at -f job.sh now",
    "echo 'batch' | bash",
    "time at now",
    "curl -#k https://localhost/health",
    'echo "$(batch)"',
    'echo "$(at -f job.sh now)"',
    "sudo -u root at -f job.sh now",
    "echo batch | sudo -u root bash",
    "env -S'curl -k https://localhost/health'",
    "! at -f job.sh now",
    "if at -f job.sh now; then echo ok; fi",
    "while at -f job.sh now; do break; done",
    "echo batch | runuser -u root -- bash",
    "at -c 5 | bash",
    'eval "$(at -c 5)"',
    "echo batch | runuser -u root -- sh",
    "echo batch | busybox sh",
    "echo batch | su root",
    "echo batch | fish",
    "nice at now",
    "timeout 5 at now",
    "setsid at now",
    "stdbuf -o0 at now",
    "time -p at -f job.sh now",
    "2>&1 at -f job.sh now",
    "echo batch | /usr/sbin/runuser -u root -- bash",
    "at 17:00 tomorrow < job.sh",
    "at 5pm -f job.sh",
    "at -fjob.sh now",
    "at -t202512251700",
    "at -mf job.sh now",
    "at 2025-12-25 < job.sh",
    "at 122525",
    "at Dec 25",
    "env -S'at now'",
    "env -S'batch'",
    "printf 'batch\\n' | sh",
    "printf 'batch\\040-f\\040job.sh\\n' | sh",
    "echo -e 'batch\\x20' | sh",
    "printf 'at\\040now\\n' | sh",
    "at <job.sh now",
    "at 5PM <job.sh",
    "bash -c batch ignored",
    "CRONTAB -r",
    "CURL -k https://localhost/health",
    "AT now",
    "at<job.sh now",
    "at <'job file.sh' now",
    "at >out.log now <job.sh",
    "echo 'rm -rf ~/work' | batch 2>/dev/null",
    "batch 0<job.sh",
    "printf 'batch 2>&1\\n' | sh",
    "bash -c'batch x'",
    "printf 'echo hello\\n' | batch # schedule when idle",
    "at &>/dev/null now",
    "at&>/dev/null now",
    "at 2>err.log now",
    "csrutil >/dev/null disable",
    "at + 1 minute",
    "at 17:00UTC",
    "batch now",
    "batch 17:00",
    "curl --proxy-insecure --proxy https://proxy.example https://example.com",
    "curl --doh-insecure --doh-url https://doh.example https://example.com",
  ])("sends %s to a human", (command) => {
    expect(check(command)).toBeDefined();
  });

  it.each([
    "curl -fsSL https://example.com/data.json",
    "wget -k https://example.com/docs/",
    "git log --oneline",
    "systemctl status nginx",
    "bash scripts/setup.sh",
    "sudo -u www-data ls /var/www",
    "su - deploy",
    "su root -- ./run-tests.sh",
    "runuser --user=root -- ./run-tests.sh",
    "git config --global alias.co checkout",
    "pnpm test > out.log 2>&1",
    "pnpm test>out.log 2>&1",
    "sort -k2 </tmp/in.txt >/tmp/out.txt",
    "git config --global core.editor vim",
    "git -c core.pager=less log",
    "curl -4 https://example.com",
    "pnpm build &> build.log",
    "printf '%5s done\\n' ok | bash",
    "printf '%f\\n' 1.5",
    "printf '%+d items\\n' 3 | bash",
    "runuser -u deploy -- git -c color.ui=never log",
    "su deploy -c 'pnpm test'",
    "git config --global core.autocrlf no",
    "atq",
    "at -l",
    "pnpm test \\\n  --reporter verbose",
    "GH_PAGER=cat gh pr diff 291",
    "npx tsx --eval 'console.log(\"at end of line\")'",
    "(cd app && at_home=1 make)",
    'git commit -m "the command at hand"',
    'echo "processing time at scale"',
    "at -l",
    'echo "added a fallback at 60s"',
    'echo "the curriculum at 4e-6"',
    "for batch in batches; do echo; done",
    "git show --stat --patch HEAD",
    "git diff --stat -- src/app.ts",
    "curl -K curl.conf https://example.com",
    "brew services list",
    "brew services --verbose list",
    "brew services --file dev.plist list",
    'git commit -m "look at next steps"',
    'git commit -m "looked at saturation and monitoring"',
    'echo "meet at Monday\'s standup"',
    'echo "meet at Monday’s standup"',
    "brew install postgresql@17",
    "systemd-run --user --scope pnpm test",
    "git commit --no-verify -m wip",
  ])("leaves %s to Jev", (command) => {
    expect(check(command)).toBeUndefined();
  });

  // The price of not parsing: a mention in data asks too.
  it.each([
    "cat src/crontab.ts",
    'rg "launchctl load" README.md',
    "command -v crontab",
    "cat <<'EOF' > NOTES.md\nsystemctl enable dev.service\nEOF\necho done",
    "cat <<-EOF\n\tsee crontab -r\n\tEOF",
    "echo done # example: systemctl enable dev.service; crontab -r",
    "npm install --strict-ssl",
    "git grep 'http.sslVerify=false'",
    "git grep -c 'http.sslVerify=false'",
    "git config get --value false http.sslVerify",
    "cat <<'EOF' | grep bash\ncrontab -r\nEOF",
    "grep crontab <<< 'crontab -r'",
    "echo '> crontab -r'",
    "cat <<EOF\n\\$(crontab -r)\nEOF",
    "echo 'crontab -r is dangerous' > notes.txt",
    "git grep 'core.editor=crontab -r'",
    "git config --get core.editor 'crontab -r'",
    "printf 'echo %s\\n' 'crontab -r' | bash",
    "printf 'echo %s\\n' '\\ncrontab -r' | bash",
    "bash -c'true x' 'crontab -r'",
    "git config http.sslVerify",
    "git config --global http.sslVerify",
    "bash -c 'printf \"%s\\n\" \"$1\"' -- 'crontab -r'",
    "sudo -u deploy ls <<< 'crontab -r'",
    "git config --get-regexp http.sslVerify false",
    "cat <<'EOF' > setup.md\nRun: crontab -r\nEOF",
    "runuser -u root -- ssh -c aes128-ctr host 'crontab -r'",
    "crontab -l",
    "crontab -u me -l",
    "python - <<'PY'\nimport os\nos.system('crontab -l')\nPY",
    // Known over-asks of matching across unquoted text (accepted for v1).
    "curl -o./package.json https://example.com/package.json",
    "curl https://example.com; sort -k1 data.txt",
  ])("asks about %s, which only mentions a listed command", (command) => {
    expect(check(command)).toBeDefined();
  });

  // Text built while the command runs is Jev's to judge (its `opaque` question).
  it.each([
    "printf 'echo %f\\n' 1 | bash",
    "printf '\\Uffffffff\\n' x | bash",
    "printf '%1000000000s\\n' x | bash",
  ])("leaves runtime-built %s to Jev", (command) => {
    expect(check(command)).toBeUndefined();
  });

  it("stays fast on long, repetitive commands", () => {
    const inputs = [
      `${"sudo ".repeat(2000)}echo ok`,
      `${"curl ".repeat(2000)}echo ok`,
      `${"systemctl ".repeat(2000)}status`,
      `${"at ".repeat(4000)}x`,
      "curl".repeat(4000),
      "launchctl".repeat(1700),
    ];
    for (const command of inputs) {
      const start = performance.now();
      check(command);
      expect(performance.now() - start).toBeLessThan(200);
    }
  });

  it("checks a shell alias's command, and nothing else in the input", () => {
    expect(neverAutoAllow({ cmd: "crontab -r" })).toBe("changes scheduled jobs");
    expect(neverAutoAllow({ command: "ls", description: "then run crontab -r" })).toBeUndefined();
  });
});
